Repository Coding-Web-Community/CodingBump, pull requests merged in 2020-10, with the labels that each got.

#1 Added bump endpoint
  api/README.md
  api/go.mod
  api/go.sum
  api/src/main.go
  api/src/store.go
  api/store.json
Labels: hacktoberfest

#2 Updated acoording to reviewers' requests
  .gitignore
  api/README.md
  api/go.mod
  api/src/bump.go
  api/src/go.mod
  api/src/go.sum
  api/src/main.go
  api/src/store.go
  api/store.json
Labels: documentation, enhancement, hacktoberfest

#3 Foobar/development/bot
  discordBot/README.md
  discordBot/cog/ErrorHandler.py
  discordBot/main.py
  discordBot/requirements.txt
  discordBot/static/fist.png
  discordBot/static/perms.png
  discordBot/static/ping.png
  discordBot/static/raise.png
  discordBot/static/stop.png
  discordBot/static/think.png
Labels: hacktoberfest, hacktoberfest-accepted

#4 Added test code + fetch route
  api/README.md
  api/src/bump_test.go
  api/src/fetch.go
  api/src/main.go
  api/src/store.go
Labels: documentation, enhancement, hacktoberfest

#5 Added TravisCI testing
  .travis.yml
  README.md
  api/README.md
Labels: enhancement, hacktoberfest

#6 First merge from dev into main
  .gitignore
  .travis.yml
  README.md
  api/README.md
  api/src/bump.go
  api/src/bump_test.go
  api/src/fetch.go
  api/src/go.mod
  api/src/go.sum
  api/src/main.go
  api/src/store.go
  discordBot/README.md
  discordBot/cog/ErrorHandler.py
  discordBot/main.py
  discordBot/requirements.txt
  discordBot/static/fist.png
  discordBot/static/perms.png
  discordBot/static/ping.png
  discordBot/static/raise.png
  discordBot/static/stop.png
  discordBot/static/think.png
  website/README.md
Labels: hacktoberfest
